name: data_connection_checker
description: A pure Dart library that checks for internet by opening a socket to a list of specified addresses, each with individual port and timeout. Defaults are provided for convenience.
version: 0.4.0
author: Paulo Alexandre <pauloalexandre820@gmail.com>
repository: https://github.com/PAULOTEK/data_connection_checker
issue_tracker: https://github.com/PAULOTEK/data_connection_checker/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

# dependencies:

dev_dependencies:
  test: ^1.24.9
  pedantic: ^1.11.1
